exec-once = nm-applet --indicator &
exec-once = waybar &
exec-once = ~/.local/bin/rice --apply
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = awww-daemon
exec-once = sleep 1 && awww img $(cat ~/.cache/current-wallpaper) --transition-type fade --transition-duration 1
exec-once = ollama serve
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = mako
