#monitor = eDP-1, 2560x1600@240, 0x0, 1.6, bitdepth, 10, cm, hdr
monitor = desc:Samsung Display Corp. 0x41A4, 2560x1600@240, 0x0, 1.6, bitdepth, 10, cm, hdr
monitor = HDMI-A-1, preferred, auto, 1


$terminal = alacritty
$menu = rofi -show drun -show-icons -icon-theme "Papirus"
$browser = firefox
$fileManager = thunar

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/lookandfeel.conf
source = ~/.config/hypr/input.conf
