input {
    kb_layout = us,gr
    #kb_options = grp:alt_shift_toggle
    accel_profile = flat
    follow_mouse = 1
    sensitivity = 0.7
    repeat_rate = 50
    repeat_delay = 240

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        scroll_factor = 0.4
    }
}

gesture = 3, horizontal, workspace
gesture = 3, up, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 20%+
gesture = 3, down, dispatcher, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 20%-
