$mainMod = SUPER

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, W, exec, $menu
bind = $mainMod, E, exec, $browser
bind = $mainMod, R, exec, $fileManager
bind = $mainMod, M, exec, spotify

#bind = $mainMod, A, exec, $HOME/.local/src/magi-app/launch.sh
bind = $mainMod, A, exec, quickshell -c hyprquickpaper
bind = $mainMod, I, exec, ~/.local/bin/magi-toggle
bind = $mainMod, S, exec, hyprshot -m region --clipboard
bind = $mainMod, B, exec, killall waybar || waybar
bind = $mainMod, V, exec, cliphist list | rofi -dmenu -display-columns 2 | cliphist decode | wl-copy

bind = $mainMod, C, killactive,
bind = $mainMod, T, togglefloating
bind = $mainMod, P, pin
bind = $mainMod, F, fullscreen
bind = $mainMod, Tab, exec, rofi -show window
bind = $mainMod SHIFT, M, exec, hyprctl keyword general:layout master
bind = $mainMod SHIFT, D, exec, hyprctl keyword general:layout dwindle
bind = $mainMod ALT, shift_L, exec, hyprctl switchxkblayout all next

bind = $mainMod, H,  movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K,    movefocus, u
bind = $mainMod, J,  movefocus, d

bind = $mainMod SHIFT, H,  movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K,    movewindow, u
bind = $mainMod SHIFT, J,  movewindow, d

#bind = $mainMod, 1, workspace, 1
#bind = $mainMod, 2, workspace, 2
#bind = $mainMod, 3, workspace, 3
#bind = $mainMod, 4, workspace, 4
bind = $mainMod SHIFT, 1, workspace, 1
bind = $mainMod SHIFT, 2, workspace, 2
bind = $mainMod SHIFT, 3, workspace, 3
bind = $mainMod SHIFT, 4, workspace, 4

bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

#bind = $mainMod SHIFT, 1, movetoworkspace, 1
#bind = $mainMod SHIFT, 2, movetoworkspace, 2
#bind = $mainMod SHIFT, 3, movetoworkspace, 3
#bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod, 1, movetoworkspace, 1
bind = $mainMod, 2, movetoworkspace, 2
bind = $mainMod, 3, movetoworkspace, 3
bind = $mainMod, 4, movetoworkspace, 4

bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, grave,       togglespecialworkspace, magic
bind = $mainMod SHIFT, grave, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up,   workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = , XF86AudioMute,         exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = , XF86AudioMicMute,      exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = , XF86AudioNext,         exec, playerctl next
bindl  = , XF86AudioPause,        exec, playerctl play-pause
bindl  = , XF86AudioPlay,         exec, playerctl play-pause
bindl  = , XF86AudioPrev,         exec, playerctl previous
bindel = , XF86MonBrightnessUp,   exec, brightnessctl --device='intel_backlight' set 20%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl --device='intel_backlight' set 20%-
