xwayland {
    force_zero_scaling = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = music-player
    match:class = ^(spotify)$
    workspace = special:magic
}

windowrule {
    name = magi-dashboard
    match:class = ^(magi-dashboard)$
    float = yes
    move = 0 0
    size = 500 1000
}
