-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "music-player",
    match = {
        class = "^(spotify)$",
    },
    workspace = "special:magic",
})

hl.window_rule({
    name  = "magi-dashboard",
    match = {
        class = "^(magi-dashboard)$",
    },
    float = true,
    move = { 0, 0 },
    size = { 500, 1000 },
})
